Repository CrackerSuman/Hacktoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#1 Leetcode Find Median Sorted Arrays solution
  contributors/findMedianSortedArrays.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#7 New languages added
  C++/HelloWorld.cpp
  C++/MatrixMultiplication.cpp
  C++/PalindromeNumber.cpp
  Java/Adding two Numbers.java
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#9 Added some codes
  JS/findLongestWordLength.js
  Python/calculator.py
  Python/excel_to_csv.py
  Python/snakegame.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#10 added resume shortlist code
  Python/resume_shortlist.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#16 calc in java
  C++/Number_of_words.cpp
  Java/Calculator.java
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022
